import type { TimelineExperience } from "./types";

// Clean, structured experience data
export const experienceTimeline: TimelineExperience[] = [
  {
    id: "true-anomaly",
    companyName: "True Anomaly",
    roles: [
      {
        title: "Principal Software Engineer",
        accomplishments: [
          "Continuing to spearhead the front-end architectural design and development of the Mosaic Software Platform, a command & control/mission planning software platform.",
          "Aligning front-end technical strategy with long-term business goals.",
          "Overhauled the front-end engineering hiring and onboarding process during a period of 2x headcount growth.",
        ],
        startDate: new Date(2025, 7),
      },
      {
        title: "Staff Software Engineer",
        accomplishments: [
          "Continued to establish front-end best practices and architectural standards for the Mosaic Software Platform, ensuring scalability, maintainability, and performance.",
          "Collaborated closely with product/design, QA, backend and space operations teams to ensure architecture met performance, scalability, and user experience requirements.",
          "Mentored new React developers, fostering a culture of continuous learning and knowledge sharing within the team.",
        ],
        startDate: new Date(2025, 1),
        endDate: new Date(2025, 7),
      },
      {
        title: "Senior Software Engineer",
        accomplishments: [
          "Architected the strategic migration of a legacy Unity application to a React/TypeScript stack, ensuring a seamless transition while maintaining core functionalities.",
          "Formalized the enterprise design system and UI pattern library, significantly improving development efficiency and consistency across the platform.",
          "Integrated React Three Fiber (R3F) to maintain high-fidelity 3D visualization while leveraging React’s reconciliation for UI overlays.",
        ],
        startDate: new Date(2023, 11),
        endDate: new Date(2025, 1),
      },
    ],
    startYear: 2023,
    endYear: null,
    companyUrl: "https://www.trueanomaly.space",
    technologies: [
      "TypeScript",
      "React",
      "Jotai",
      "Tailwind CSS",
      "Base UI",
      "D3.js",
      "React Three Fiber",
    ],
  },
  {
    id: "benbeck-dev",
    companyName: "BenBeck.dev",
    roles: [
      {
        title: "Software Architect",
        accomplishments: [
          "Architected the PFG CustomerFirst ordering interface utilizing advanced state-management patterns to synchronize complex multi-line orders with real-time inventory updates.",
          "Established and led the front-end technical governance for a team of 10 engineers, implementing a modular component architecture and strict TypeScript configurations to ensure code reusability and type safety.",
          "",
          "Architected and developed a suite of web-based configuration tools for PowerBI.Tips, enabling developers to programmatically generate and manage complex Power BI theme files and report templates.",
          "Implemented complex state-management patterns to handle real-time UI previews and dynamic code generation, allowing users to export production-ready .pbit and .json files directly from the browser.",
        ],
        startDate: new Date(2021, 0),
        endDate: new Date(2023, 11),
      },
    ],
    startYear: 2021,
    endYear: 2023,
    companyUrl: "https://benbeck.dev",
    technologies: [
      "Microsoft Azure",
      "TypeScript",
      "React",
      "Redux",
      "React Native",
      "Node.js",
      "SQL Server",
    ],
  },
  {
    id: "adm",
    companyName: "ADM",
    roles: [
      {
        title: "Senior Software Engineer",
        accomplishments: [
          "Designed and implemented production and supply chain optimization tools for enhanced efficiency.",
          "Created a production scheduling tool that significantly reduced production time by over 30%.",
          'Developed a user-friendly platform for creating customized "tasting sessions" to attract multiple potential clients.',
        ],
        startDate: new Date(2020, 3),
        endDate: new Date(2021, 3),
      },
    ],
    startYear: 2020,
    endYear: 2021,
    companyUrl: "https://www.adm.com",
    contractCompany: "Apex Systems",
    contractCompanyUrl: "https://www.apexsystems.com",
    technologies: [
      "Microsoft Azure",
      "C#",
      "TypeScript",
      "Angular",
      "NgRx",
      "D3.js",
      "React",
      "SQL Server",
    ],
    contract: true,
  },
  {
    id: "concurrency-senior",
    companyName: "Concurrency, Inc.",
    roles: [
      {
        title: "Senior Software Developer",
        accomplishments: [
          "Developed POC/MVP solutions using NLP for invoice processing with an exceptional accuracy rate of over 98%.",
          "Designed and implemented a proactive monitoring system that resulted in significant cost savings through effective risk management alerts.",
        ],
        startDate: new Date(2019, 5),
        endDate: new Date(2020, 3),
      },
      {
        title: "Blockchain Architect",
        accomplishments: [
          "Led a team of 3 developers in the successful implementation of customized consortium blockchain POC solutions.",
          "Demonstrated the value and applicability of private/consortium blockchains through presales efforts and use case evangelism.",
        ],
        startDate: new Date(2019, 0),
        endDate: new Date(2019, 5),
      },
    ],
    startYear: 2019,
    endYear: 2020,
    companyUrl: "https://www.concurrency.com",
    technologies: [
      "Microsoft Azure",
      "C#",
      "Solidity",
      "TypeScript",
      "Angular",
      "React",
      "SQL Server",
    ],
  },
  {
    id: "microsoft",
    companyName: "Microsoft",
    roles: [
      {
        title: "Software Engineer",
        accomplishments: [
          "Developed an Ethereum (Parity PoA) template for Microsoft Azure, enabling streamlined blockchain deployment.",
          "Contributed to the development of 5 other ledger templates including Hyperledger Fabric and IPFS, expanding the range of options available.",
          "Conducted multiple POCs to evaluate the potential of emerging ledger technologies, providing valuable insights for future advancements.",
        ],
        startDate: new Date(2018, 7),
        endDate: new Date(2019, 0),
      },
    ],
    startYear: 2018,
    endYear: 2019,
    companyUrl: "https://www.microsoft.com",
    contractCompany: "TEKsystems",
    contractCompanyUrl: "https://www.teksystems.com",
    technologies: [
      "Microsoft Azure",
      "Bash",
      "PowerShell",
      "Solidity",
      "C#",
      "TypeScript",
      "Node.js",
      "Python",
    ],
    contract: true,
  },
  {
    id: "concurrency-early",
    companyName: "Concurrency, Inc.",
    roles: [
      {
        title: "Software Developer",
        accomplishments: [
          "Solely developed a real-time fetal/maternal heartrate & vitals monitoring portal.",
          "Assisted with the development of an IoT solution for foundry management.",
          "Architected & developed numerous web portals and internal IT tools.",
          "Assisted with an IdentityServer solution for a smaller financial company.",
        ],
        startDate: new Date(2016, 10),
        endDate: new Date(2018, 7),
      },
      {
        title: "Associate Software Developer",
        accomplishments: [
          "Joined the Modern Applications team (focused on cloud, web, security, IoT and blockchain).",
          "Developed & architected a data aggregation portal for mid-large sized dental providers.",
        ],
        startDate: new Date(2016, 6),
        endDate: new Date(2016, 10),
      },
    ],
    startYear: 2016,
    endYear: 2018,
    companyUrl: "https://www.concurrency.com",
    technologies: [
      "Microsoft Azure",
      "C#",
      "TypeScript",
      "Angular",
      "AngularJS",
      "D3.js",
      "SQL Server",
      "Power BI",
    ],
  },
  {
    id: "advicent",
    companyName: "Advicent",
    roles: [
      {
        title: "Software Development Intern",
        accomplishments: [
          "Primarily worked on front-end web applications targeted for financial advisors and their respective clients.",
          "Assisted in back-end development and integration of 3rd party financial APIs.",
        ],
        startDate: new Date(2015, 5),
        endDate: new Date(2016, 2),
      },
    ],
    startYear: 2015,
    endYear: 2016,
    companyUrl: "https://www.advicentsolutions.com",
    technologies: [
      "JavaScript",
      "AngularJS",
      "jQuery",
      "C#",
      "WCF",
      "SQL Server",
      "HTML",
      "CSS",
      "SASS",
    ],
    internship: true,
  },
  {
    id: "cognex",
    companyName: "Cognex",
    roles: [
      {
        title: "Software Engineering Intern",
        accomplishments: [
          "Developed an internal tool for managing, monitoring and controlling internal office resource usage.",
          "Worked closely with the QA team performing UI automation testing.",
        ],
        startDate: new Date(2014, 5),
        endDate: new Date(2014, 11),
      },
    ],
    startYear: 2014,
    endYear: 2014,
    companyUrl: "https://www.cognex.com",
    technologies: [
      "JavaScript",
      "Node.js",
      "Express.js",
      "jQuery",
      "C#",
      "WCF",
      "XML",
      "HTML",
      "CSS",
    ],
    internship: true,
  },
];
